### ISSUE TITLE
mako已支持windows，请更新他

### ISSUE THREAD

**Issue by 461201574asd** [umijs/umi-plugin-mako#11]

**Comment by xiaohuoni** [comment]
8分钟前，发的包，明天更新吧。今天测试一下

**Comment by xiaohuoni** [comment]
mako 版本回退了，所以没有更新

**Comment by xiaohuoni** [comment]
先更新到 0.8.11 https://www.npmjs.com/package/@umijs/mako-win32-x64-msvc/v/0.8.11

**Comment by xiaohuoni** [comment]
@461201574asd + umi-plugin-mako@0.0.11 请帮忙验证一下

**Comment by xiaohuoni** [comment]
@461201574asd 不过大概率还不可用，这里有一个 0.8.11 的 bug https://github.com/umijs/umi/issues/12694

**Comment by linyxria** [comment]
0.8.11 启动报以下错误：

thread 'tokio-runtime-worker' panicked at crates/mako/src/plugins/duplicate_package_checker.rs:108:92:
called `Result::unwrap()` on an `Err` value: Error("unexpected end of input while parsing minor version number")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by tuzkituan** [comment]
> 0.8.11 启动报以下错误：
> 
> thread 'tokio-runtime-worker' panicked at crates/mako/src/plugins/duplicate_package_checker.rs:108:92: called `Result::unwrap()` on an `Err` value: Error("unexpected end of input while parsing minor version number") note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I have the same issue

**Comment by telanflow** [comment]
> I have the same issue

I have the same issue

**Comment by xiaohuoni** [comment]
+ umi-plugin-mako@0.0.12

**Comment by xiaohuoni** [comment]
@telanflow @tuzkituan @linyxria @461201574asd try using this version --- umi-plugin-mako@0.0.12

**Comment by lewisnguyen2804** [comment]
> @telanflow @tuzkituan @linyxria @461201574asd try using this version --- umi-plugin-mako@0.0.12
I'm facing another issue
![image](https://github.com/user-attachments/assets/96be988a-6bb5-42d0-9ad7-9453c0d6c511)

**Comment by telanflow** [comment]
> > @telanflow @tuzkituan @linyxria @461201574asd try using this version --- umi-plugin-mako@0.0.12
> 
> Still errors
> 
> ![image](https://private-user-images.githubusercontent.com/68054091/375647383-96be988a-6bb5-42d0-9ad7-9453c0d6c511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjYzMTksIm5iZiI6MTcyODY2NjAxOSwicGF0aCI6Ii82ODA1NDA5MS8zNzU2NDczODMtOTZiZTk4OGEtNmJiNS00MmQwLTlhZDctOTQ1M2MwZDZjNTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE3MDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkOGRlYTA1NDJlMDllNGZhYWM0OWU3ZDFmZTU2ODhhNmI3MDAyNDNlMjQyMTg4MDFhOGUwMDIwNWRhYWFiYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pV3RLA6fUkb3zSyTXPA6I-onIlQhMHqEJZjMVuT7TcQ)

Me too

![image](https://github.com/user-attachments/assets/9237babf-2fb7-45a2-96d2-14ad6be76133)

**Comment by xiaohuoni** [comment]
https://github.com/umijs/mako/issues/1632

**Comment by hughes-hc** [comment]
![image](https://github.com/user-attachments/assets/6d8ccc52-451a-4d73-8a84-c0d43ee794c2)
![image](https://github.com/user-attachments/assets/47bd937e-d5a0-4c88-8d00-907b8ff78731)

启动之后控制台在报错

**Comment by BeDay** [comment]
![4{~ZSC`8Z`}POU3FV{M`TIC](https://github.com/user-attachments/assets/7c48d63f-df41-4d91-88d5-2dfce2cd0597)
最后会报错

**Comment by BeDay** [comment]
![image](https://github.com/user-attachments/assets/8cdd679d-6542-4724-a8cd-2943b02ff1d8)
开模式

**Comment by xiaohuoni** [comment]
+ umi-plugin-mako@0.0.13
