### ISSUE TITLE
mako使用@umijs/plugin-qiankun；构建报错 chunk of umi not found.

### ISSUE THREAD

**Issue by zhu2018** [umijs/umi-plugin-mako#16]
使用脚手架安装后即可复现

版本如下
umi@3.5.43
@umijs/plugin-qiankun@2.44.1
umi-plugin-mako@0.0.12
配置如下
`mako:{}`
`qiankun:{slave:{}}
`

开启构建后会报下面错
AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at /Users/admin/Desktop/menu-finance/umi3/node_modules/.pnpm/@umijs+preset-built-in@3.5.43_wcqkhtmu7mswc6yz4uyexck3ty/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (/Users/admin/Desktop/menu-finance/umi3/node_modules/.pnpm/@umijs+preset-built-in@3.5.43_wcqkhtmu7mswc6yz4uyexck3ty/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
    at /Users/admin/Desktop/menu-finance/umi3/node_modules/.pnpm/@umijs+preset-built-in@3.5.43_wcqkhtmu7mswc6yz4uyexck3ty/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:189:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/admin/Desktop/menu-finance/umi3/node_modules/.pnpm/@umijs+preset-built-in@3.5.43_wcqkhtmu7mswc6yz4uyexck3ty/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
    at _next (/Users/admin/Desktop/menu-finance/umi3/node_modules/.pnpm/@umijs+preset-built-in@3.5.43_wcqkhtmu7mswc6yz4uyexck3ty/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

**Comment by rendeyuwei** [comment]
+1

**Comment by bonboru93** [comment]
+1

**Comment by ace-han** [comment]
+1

**Comment by xiongying1994** [comment]
别+1了，怎么解决这个问题啊
